' Диаграмма контекста (С4) AS IS

@startuml

!include ../templates/C4.puml
!include ../templates/C4_Context.puml
!include ../templates/C4_Container.puml
!include ../templates/C4_Component.puml

Title Диаграмма контекста 'Кинобездна' AS-IS

System_Boundary(enterprise, "Компания 'Кинобездна'") {
    System(cinemaAbyss, "Система 'Кинобездна'", "Монолит на Go")
}
Person(user, "Пользователь", "Ноутбуки, смарт-ТВ, мобильные устройства")
System_Ext(payments, "Платежная система")
System_Ext(cinemas, "Онлайн-кинотеатры")
System_Ext(recommendation, "Рекомендательная система")
System_Ext(S3, "S3")

Rel(user, cinemaAbyss, "покупает подписки, выбирает, просматривает и оценивает фильм, составляет список избранного")
Rel(cinemaAbyss, recommendation, "использует рекомендации")
Rel(cinemaAbyss, payments, "выставляет платёжные документы")
Rel(cinemaAbyss, cinemas, "запрашивает данные")
Rel(cinemaAbyss, S3, "хранит данные")

@enduml