apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewogICAgICAgICAgICAiYXV0aCI6ICJTM0p2ZFdkc2FXdHZkanBuYUhCZk5YZzBWR3BUYURVd1lrRjRhak5XYkVSdVpEazVWVlJEVUVoWlJGY3dNRE5SVlZsSSIKICAgICAgICB9CiAgICB9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIKfQ==
type: kubernetes.io/dockerconfigjson
